/** Основные SEO-маршруты (как в ТЗ) + внутренние статьи под НЧ */

export const primarySeoRoutes = [
  { href: "/lucky-bear-bonus", label: "Бонусы Lucky Bear" },
  { href: "/lucky-bear-otzyvy", label: "Отзывы" },
  { href: "/lucky-bear-registraciya", label: "Регистрация и вход" },
  { href: "/lucky-bear-skachat", label: "Скачать приложение" },
  { href: "/lucky-bear-uzbekistan", label: "Узбекистан" },
  { href: "/lucky-bear-kazakhstan", label: "Казахстан" },
  { href: "/lucky-bear-rossiya", label: "Россия" },
  { href: "/lucky-bear-promokod", label: "Промокоды" },
  { href: "/lucky-bear-igry", label: "Игры" },
  { href: "/sloty-lucky-bear", label: "Слоты" },
] as const;

/** Программные длинные страницы */
export const programmaticSlugs = [
  "lucky-bear-kazino-otzyvy-realnye",
  "laki-bir-kazino-bonus-za-registraciyu",
  "igrat-v-lucky-bear-na-dengi",
  "skachat-lucky-bear-na-android",
  "luchshie-sloty-lucky-bear",
  "lucky-bear-zerkalo-rabochee",
  "luckybear-vhod-lichniy-kabinet",
  "lucky-bear-bonus-bez-depozita",
  "lucky-bear-fribety-i-akcii",
  "lucky-bear-mobilnaya-versiya-brauzer",
  "lucky-bear-vyplaty-i-limiti",
  "lucky-bear-verifikaciya-akkaunta",
  "lucky-bear-keshbek-programma",
  "lucky-bear-turniry-i-liderbordi",
  "lucky-bear-live-igri",
  "lucky-bear-prilozhenie-ios-kak-ustanovit",
  "lucky-bear-oficialnyy-sayt-obzor",
  "lucky-bear-nadezhnost-i-litsenziya",
  "lucky-bear-kriptovalyuty-popolnenie",
  "lucky-bear-minimalnyy-depozit",
  "lucky-ber-casino-chasto-pishut-s-oshibkoy",
  "luckybear-promokod-s-aktivatsiey",
  "lucky-bear-ohota-za-bonusami",
  "sloty-laki-bir-reyting-volatilnosti",
  "lucky-bear-bonus-na-pervyy-depozit",
  "lucky-bear-bezopasnost-dannyh",
  "lucky-bear-podderzhka-24-7",
  "lucky-bear-igrovye-avtomaty-klassika",
  "lucky-bear-dzhekpoty-progressivnye",
  "lucky-bear-programma-loyalnosti-urovni",
  "lucky-bear-kazahstan-tyenge-limits",
  "lucky-bear-uzbekistan-sum-popolnenie",
  "lucky-bear-rossiya-rubli-vyvody",
  "lucky-bear-slots-book-dead-obzor",
  "lucky-bear-slots-sweet-bonanza-obzor",
  "lucky-bear-slots-gates-olympus-obzor",
  "lucky-bear-strategiya-bankroll",
  "lucky-bear-otvetstvennaya-igra",
  "lucky-bear-sravnenie-s-drugimi-kazino",
  "kak-poluchit-keshbek-lucky-bear",
] as const;

export type ProgrammaticSlug = (typeof programmaticSlugs)[number];
